version: "3.9"

services:
  app:
    build: .
    container_name: violence-detection
    ports:
      - "8765:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
    restart: unless-stopped
    